exclude:
  - package.json
  - node_modules
  - gulpfile.js

github:
  baseurl: '/iren-says-blog/'

baseurl: '/'

defaults:
  - scope:
      path: ''
      type: 'category'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:slugified_categories/:title'
      excerpt_separator: <!--more-->
  - scope:
      path: ''
    values:
      layout: 'default'

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: ['categories', 'tags']
  layout: archive
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    day: '/archives/day/:year-:month-:day/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
