exclude:
  - package.json
  - node_modules
  - gulpfile.js

collections:
  category:
    output: true

github:
  baseurl: '/iren-says-blog/'

baseurl: '/'

defaults:
  - scope:
      path: ''
      type: 'category'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:slugified_categories/:title'
      excerpt_separator: <!--more-->
  - scope:
      path: ''
    values:
      layout: 'default'
