exclude:
  - package.json
  - node_modules
  - gulpfile.js

github:
  baseurl: '/iren-says-blog/'

baseurl: '/'

defaults:
  - scope:
      path: ''
      type: 'category'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:slugified_categories/:title'
      excerpt_separator: <!--more-->
  - scope:
      path: ''
    values:
      layout: 'default'

plugins:
  - jekyll-archives
  - jekyll-paginate-v2

jekyll-archives:
  enabled: ['categories', 'tags']
  layout: archive
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    day: '/archives/day/:year-:month-:day/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # How many posts to show per page. Temporary 3 - for debugging
  per_page: 8
  debug: true
  sort_field: 'date'
  sort_reverse: true
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
